import { useState } from "react";
import { ThemeContext, useTheme, themes, alpha, ALPHA } from "../../theme";
import { themeToInputs, inputsToTheme, themeToSource } from "../../themeSource";

/* ═══════════════════════════════════════════════════════════════════════════
 * THEME EDITOR — developer tool, not a user feature
 *
 * Reached at #themes. Deliberately absent from AppHeader's NAV_ITEMS, so
 * nothing in the UI links to it.
 *
 * That is "not discoverable", which is weaker than "not reachable": the page
 * id is in useAppData's VALID_PAGES, so anyone who types the fragment gets
 * here. This was chosen knowingly over a build-time exclusion. What makes it
 * defensible is that the editor has no backend at all — saving is a download
 * the developer pastes into theme.jsx by hand, so there is no endpoint to
 * reach and nothing here can write to the server or the user's library. The
 * worst case is a confused user looking at a developer tool. If that stops
 * being acceptable, the change is an import.meta.env.DEV guard around the
 * VALID_PAGES entry and the branch in App.jsx, not a rewrite of this file.
 *
 * ── Why the preview needs no changes to any component ─────────────────────
 * The whole app reads its theme from ThemeContext, and theme.jsx exports
 * that context specifically so a caller can supply a theme object directly.
 * So the preview is a real page rendered inside a second provider holding
 * the draft. No component knows it is being previewed, nothing is mocked,
 * and there is no miniature to keep in step with the real thing the way
 * AppearanceSection's ThemePreview has to be.
 *
 * ── Why the controls do NOT render under the draft ────────────────────────
 * The controls read useTheme() and so follow whatever theme the user has
 * actually selected; only the preview pane gets the draft. This is not a
 * detail. Editing palette.bg to the same value as palette.text under a
 * single provider makes the editor itself unreadable, and the controls
 * needed to undo it are the ones that just disappeared. Splitting the two
 * means a draft can be as broken as you like and the way out stays visible.
 *
 * ── Why the control list is derived, not written out ──────────────────────
 * Fields are generated by walking the draft's own inputs, and which control
 * a value gets is decided from the value itself. No list of token names
 * appears in this file.
 *
 * A hardcoded list is the obvious alternative and it fails silently in the
 * direction that matters: add a colour to palette in theme.jsx and it simply
 * has no control here, so every theme saved from this editor carries
 * whatever the base theme happened to have for a token nobody could see.
 * Deriving means a new token gets a field the moment it exists. Same
 * reasoning as REFERENCE_SHAPE in themeSource.js — generation is hardcoded
 * so drift gets caught, display and validation are derived so they track the
 * real thing.
 *
 * ── What "save" is, and why it is a download ──────────────────────────────
 * theme.jsx is not in the shipped container. The Dockerfile's runtime stage
 * copies app/, RELEASE_NOTES.md and the BUILT frontend/dist; frontend/src
 * exists only inside the throwaway ui-builder stage. So a backend endpoint
 * that writes the theme file would work in a dev checkout and could not work
 * in the product, and the editor would behave differently depending on how
 * it was being run.
 *
 * Export sidesteps that entirely: the editor emits the source text, the
 * browser downloads it, and the developer pastes it into theme.jsx. It works
 * identically everywhere, needs no endpoint, and is the reason the route can
 * be merely undiscoverable rather than build-time excluded — there is
 * nothing behind it to reach.
 *
 * The editor does not validate the draft itself. It calls themeToSource and
 * renders whatever comes back, error included. A second set of rules here
 * would be a copy of the ones in themeSource.js, and copies of validation
 * drift in the direction where the UI says a theme is fine and the file it
 * writes is not.
 *
 * ── Accessible names are token paths ──────────────────────────────────────
 * Controls are named "palette.green", "tint.green", "type.size.xs" and so
 * on, not by bare key. Bare keys collide: palette and tint both carry green,
 * amber, red, blue, yellow, cyan and violet, and a label may name only one
 * control. Paths are also how a developer refers to these values when
 * reading a component, so a control is findable by the name it already has.
 ═══════════════════════════════════════════════════════════════════════════ */

/* A value that IS a colour, not one that merely contains one. The distinction
 * earns its keep in surface: drawerShadow is "0 4px 16px #00000066", a box
 * shadow with a colour inside it. Matching loosely would hand it a colour
 * picker, and picking a colour would replace the whole shadow with a bare
 * hex, losing the offsets and the blur with nothing to say so. */
const COLOUR_VALUE = /^(#[0-9a-fA-F]{3,8}|rgba?\([^)]*\))$/;

/* What the native colour input can actually represent: 6-digit hex and
 * nothing else, showing black for whatever it cannot parse.
 *
 * That covers most of palette and tint but by no means all of surface, which
 * carries 3-digit (#111), 8-digit with alpha (#ffffff07) and rgba() forms.
 * The swatch is disabled for those rather than made clever. An alpha-aware
 * swatch round-tripping #ffffff07 through a 6-digit picker would drop the
 * alpha, and rowHoverBg going from 3% white to solid white does not look
 * like a bug, it looks like a decision. The text field edits every form; the
 * swatch is a convenience that refuses rather than guesses. */
const HEX6 = /^#[0-9a-fA-F]{6}$/;

/* Generic CSS font keywords. A stack ending in one of these has a defined
 * outcome on every machine; a stack that does not ends at the mercy of what
 * the OS happens to have installed. */
const GENERIC_FAMILIES = new Set([
  "monospace", "sans-serif", "serif", "system-ui", "ui-monospace",
  "ui-sans-serif", "ui-serif", "cursive", "fantasy", "inherit",
]);

/* The stacks fonts.js actually bundles, offered as one-click presets.
 *
 * Typing a family that is not bundled is the exact failure that file exists
 * to prevent: the family is absent or the request fails, the stack falls
 * through to a system face, and the app looks wrong with nothing on screen
 * saying why. Remuxarr is usually deployed on a LAN with no outbound
 * internet, so that is the normal case rather than an edge one. */
const FONT_PRESETS = [
  { label: "JETBRAINS", value: "'JetBrains Mono Variable', 'JetBrains Mono', 'Courier New', monospace" },
{ label: "INTER",     value: "'Inter Variable', 'Inter', system-ui, sans-serif" },
{ label: "SYSTEM",    value: "system-ui, sans-serif" },
];

const lastFamily = (stack) => {
  const parts = String(stack).split(",");
  return parts[parts.length - 1].trim().replace(/^['"]|['"]$/g, "").toLowerCase();
};

const GROUP_LABELS = {
  palette: "PALETTE",
  tint:    "ACTION TINT",
  surface: "SURFACE",
  type:    "TYPOGRAPHY",
  radius:  "RADIUS",
  space:   "SPACING",
  size:    "GEOMETRY",
};

/* The four scalars that sit at the top of a theme rather than inside a
 * group. Named here because they are not a group and cannot be walked as
 * one — the token lists inside each group are still derived. */
const IDENTITY_KEYS = ["id", "label", "colorScheme", "blurb"];

const NAME_WIDTH = 118;

/* The DOM id a token path gets. Not the path itself.
 *
 * "palette.bg" is a legal HTML id, and label association works with it — but
 * any CSS selector built from it reads the dot as a class, so
 * querySelector("#palette.bg") looks for id="palette" class="bg" and quietly
 * returns null. Anything resolving a label to its control that way, which
 * includes Testing Library, then cannot find a control that is sitting right
 * there and correctly associated. It fails by finding nothing rather than by
 * erroring, which is the worst shape for it to take.
 *
 * So the id is sanitised and the path stays as the visible label text and
 * the swatch's aria-label. The accessible name is still the token path,
 * which is what anyone looking for the control actually knows. */
const domId = (path) => `token-${path.replace(/\./g, "-")}`;

const rowStyles = (t) => ({
  row: {
    display: "flex", alignItems: "center",
    gap: t.space.md, padding: `${t.space.xs}px 0`,
  },
  name: {
    flex: `0 0 ${NAME_WIDTH}px`, minWidth: 0, overflowWrap: "anywhere",
    color: t.palette.muted, fontSize: t.type.size.xs,
    fontFamily: t.type.mono, letterSpacing: t.type.tracking.normal,
  },
});

const inputStyle = (t, ok = true) => ({
  flex: 1, minWidth: 0,
  padding: `${t.space.xxs}px ${t.space.sm}px`,
  background: t.palette.bg,
  border: `1px solid ${ok ? t.palette.border : t.palette.red}`,
  borderRadius: t.radius.sm,
  color: t.palette.text,
  fontSize: t.type.size.sm,
  fontFamily: t.type.mono,
});

const ColourField = ({ path, value, onChange }) => {
  const t = useTheme();
  const { row, name } = rowStyles(t);
  const usable = HEX6.test(value);

  return (
    <div style={row}>
    <label htmlFor={domId(path)} style={name}>{path}</label>
    <input
    type="color"
    aria-label={`${path} swatch`}
    value={usable ? value : "#000000"}
    disabled={!usable}
    onChange={(e) => onChange(e.target.value)}
    style={{
      width: 34, height: 24, padding: 0, background: "transparent",
      border: `1px solid ${t.palette.border}`,
      borderRadius: t.radius.sm,
      cursor: usable ? "pointer" : "not-allowed",
    }}
    />
    <input
    type="text" id={domId(path)} value={value} spellCheck={false}
    onChange={(e) => onChange(e.target.value)}
    style={inputStyle(t)}
    />
    </div>
  );
};

const NumberField = ({ path, value, onChange }) => {
  const t = useTheme();
  const { row, name } = rowStyles(t);

  return (
    <div style={row}>
    <label htmlFor={domId(path)} style={name}>{path}</label>
    <input
    type="number" id={domId(path)} value={value}
    onChange={(e) => {
      /* Push a number when the field holds one, and the raw string when
       * it does not. Number("") is 0, so coercing unconditionally turns
       * a cleared field into a silent zero, and space.xl quietly
       * becoming 0 collapses padding across the whole app — which reads
       * as a layout bug, not as an empty input. Keeping the raw string
       * makes the preview visibly wrong and makes save refuse by name. */
      const raw = e.target.value;
      const n = Number(raw);
      onChange(raw.trim() !== "" && Number.isFinite(n) ? n : raw);
    }}
    style={inputStyle(t, typeof value === "number")}
    />
    </div>
  );
};

const TextField = ({ path, value, onChange }) => {
  const t = useTheme();
  const { row, name } = rowStyles(t);
  return (
    <div style={row}>
    <label htmlFor={domId(path)} style={name}>{path}</label>
    <input
    type="text" id={domId(path)} value={value} spellCheck={false}
    onChange={(e) => onChange(e.target.value)}
    style={inputStyle(t)}
    />
    </div>
  );
};

const SchemeField = ({ path, value, onChange }) => {
  const t = useTheme();
  const { row, name } = rowStyles(t);
  /* A select, not a text field. ThemeProvider writes this straight into
   * ":root { color-scheme: ... }", and CSS discards a declaration it cannot
   * parse — so a typo here does not fail, it silently stops the browser
   * theming form controls and scrollbars, which reads as the theme being
   * half-finished rather than as one bad value. */
  return (
    <div style={row}>
    <label htmlFor={domId(path)} style={name}>{path}</label>
    <select
    id={domId(path)} value={value}
    onChange={(e) => onChange(e.target.value)}
    style={inputStyle(t)}
    >
    <option value="dark">dark</option>
    <option value="light">light</option>
    </select>
    </div>
  );
};

const FontField = ({ path, value, onChange }) => {
  const t = useTheme();
  const { row, name } = rowStyles(t);
  const grounded = GENERIC_FAMILIES.has(lastFamily(value));
  const indent = NAME_WIDTH + t.space.md;

  return (
    <div style={{ padding: `${t.space.xs}px 0` }}>
    <div style={row}>
    <label htmlFor={domId(path)} style={name}>{path}</label>
    <input
    type="text" id={domId(path)} value={value} spellCheck={false}
    onChange={(e) => onChange(e.target.value)}
    style={inputStyle(t, grounded)}
    />
    </div>

    <div style={{ display: "flex", gap: t.space.xs, paddingLeft: indent }}>
    {FONT_PRESETS.map((p) => (
      <button
      key={p.label}
      onClick={() => onChange(p.value)}
      /* Three FontFields render this same set, so the visible text
       * alone names three different buttons. The path disambiguates
       * them without widening the control. */
      aria-label={`${path} ${p.label}`}
      style={{
        padding: `${t.space.hair}px ${t.space.xs}px`,
        background: "transparent",
        border: `1px solid ${t.palette.border}`,
        borderRadius: t.radius.sm,
        color: t.palette.dim,
        fontSize: t.type.size.xs,
        fontFamily: t.type.family,
        cursor: "pointer",
      }}
      >
      {p.label}
      </button>
    ))}
    </div>

    {/* Rendered in the stack being edited. No static check can tell you a
      * family failed to load; this can. A stack that fell through to a
      * system face looks nothing like JetBrains Mono or Inter, and the
      * difference is visible without knowing what went wrong. */}
      <div
      data-testid={`${path} sample`}
      style={{
        paddingLeft: indent, paddingTop: t.space.xxs,
        fontFamily: value, fontSize: t.type.size.md,
        color: t.palette.text,
      }}
      >
      Remuxarr 0123 handoff
      </div>

      {!grounded && (
        <div
        data-testid={`${path} warning`}
        style={{
          paddingLeft: indent, paddingTop: t.space.xxs,
          color: t.palette.amber, fontSize: t.type.size.xs,
          fontFamily: t.type.family,
        }}
        >
        No generic fallback, ends in {lastFamily(value) || "nothing"}
        </div>
      )}
      </div>
  );
};

const FONT_PATHS = new Set(["type.family", "type.root", "type.mono"]);

/* Which control a token gets, decided from the BASE theme's value at that
 * path — never from the value currently being typed.
 *
 * Dispatching on the live value was the first version and it was broken in a
 * way only a real keyboard shows. Clearing a colour field leaves "", which
 * stops matching COLOUR_VALUE, so the field switched from ColourField to
 * TextField mid-edit: React unmounted the input and mounted a different one,
 * and the browser dropped focus. Retyping a hex then crossed the boundary
 * again at "#123", so a single edit lost focus twice and silently discarded
 * whatever had been typed after the first keystroke.
 *
 * Whether a token is a colour is a property of the token, not of what is in
 * the box right now. Reading it from the base keeps the control stable while
 * its value is temporarily invalid, which is the whole of the time someone
 * is typing one.
 *
 * Font stacks are dispatched by path instead: "inherit" and a comma-separated
 * stack are both just strings, and nothing about either says it names a
 * typeface rather than, say, a letter-spacing. */
const TokenField = ({ path, value, baseValue, onChange }) => {
  if (path === "colorScheme") {
    return <SchemeField path={path} value={value} onChange={onChange} />;
  }
  if (FONT_PATHS.has(path)) {
    return <FontField path={path} value={value} onChange={onChange} />;
  }
  if (typeof baseValue === "number") {
    return <NumberField path={path} value={value} onChange={onChange} />;
  }
  if (COLOUR_VALUE.test(baseValue)) {
    return <ColourField path={path} value={value} onChange={onChange} />;
  }
  return <TextField path={path} value={value} onChange={onChange} />;
};

const Group = ({ label, count, open, onToggle, children }) => {
  const { palette, type, space } = useTheme();
  return (
    <div style={{ marginBottom: space.md }}>
    <button
    onClick={onToggle}
    aria-expanded={open}
    style={{
      width: "100%", display: "flex", justifyContent: "space-between",
      alignItems: "center", padding: `${space.xs}px 0`,
      background: "transparent", border: "none",
      borderBottom: `1px solid ${palette.border}`,
      color: open ? palette.amber : palette.muted,
      fontSize: type.size.xs, fontFamily: type.family,
      fontWeight: type.weight.bold,
      letterSpacing: type.tracking.widest, cursor: "pointer",
    }}
    >
    <span>{label}</span>
    <span style={{ color: palette.dim }}>{count}</span>
    </button>
    {open && <div style={{ paddingTop: space.sm }}>{children}</div>}
    </div>
  );
};

const leafCount = (v) =>
v && typeof v === "object"
? Object.values(v).reduce((n, x) => n + leafCount(x), 0)
: 1;

export const ThemeEditorPage = ({ children, isMobile = false }) => {
  const { palette, type, space, radius, themeId } = useTheme();

  /* The draft starts as a copy of whichever theme is selected. themeToInputs
   * deep-copies, so editing the draft cannot reach back into the themes
   * singleton the rest of the app is rendering from. */
  const [baseId, setBaseId] = useState(themeId);
  const [inputs, setInputs] = useState(() => themeToInputs(themes[themeId]));
  /* A frozen copy of what was loaded, used only to decide which control each
   * token gets. Never edited, so the choice cannot change under the cursor. */
  const [base, setBase] = useState(() => themeToInputs(themes[themeId]));
  const [open, setOpen] = useState(() => new Set(["palette"]));

  const draft = inputsToTheme(inputs);

  /* Recomputed every render rather than on a button press, so the error is
   * live feedback while typing rather than a surprise at the end. It is the
   * serialiser's own message, naming the token path it refused. */
  let source = null;
  let sourceError = null;
  try {
    source = themeToSource(inputs);
  } catch (err) {
    sourceError = err.message;
  }

  const download = () => {
    const blob = new Blob([source], { type: "text/javascript" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${inputs.id}.theme.js`;
    a.click();
    // The click starts the fetch synchronously, so the URL has served its
    // purpose by the time this runs and leaving it alive leaks for the
    // lifetime of the document.
    URL.revokeObjectURL(url);
  };

  /* Clone along the path being written, share everything else. Writing in
   * place would still repaint, because the top-level object is replaced
   * either way, but it breaks the moment anything downstream is memoised on
   * a group's identity — and that is the kind of bug that shows up as one
   * control silently not working. */
  const setAt = (path, value) => setInputs((prev) => {
    const next = { ...prev };
    let cur = next;
    for (let i = 0; i < path.length - 1; i++) {
      cur[path[i]] = { ...cur[path[i]] };
      cur = cur[path[i]];
    }
    cur[path[path.length - 1]] = value;
    return next;
  });

  const resetTo = (id) => {
    setBaseId(id);
    setInputs(themeToInputs(themes[id]));
    setBase(themeToInputs(themes[id]));
  };

  const toggle = (key) => setOpen((prev) => {
    const next = new Set(prev);
    if (next.has(key)) next.delete(key); else next.add(key);
    return next;
  });

  /* Walk a value into fields, descending wherever it is an object. Recursive
   * rather than fixed-depth so a group gaining nesting keeps working. The
   * path built here is both the control's accessible name and the argument
   * to setAt, so the label and the value it writes cannot disagree. */
  const renderValue = (path, value, baseValue) => {
    const name = path.join(".");
    if (value && typeof value === "object") {
      return (
        <div key={name} style={{ marginBottom: space.sm }}>
        <div style={{
          color: palette.dim, fontSize: type.size.xs,
          fontFamily: type.mono, letterSpacing: type.tracking.wide,
          paddingTop: space.xs,
        }}>
        {name}
        </div>
        {Object.entries(value).map(([k, v]) =>
          renderValue([...path, k], v, baseValue?.[k]))}
          </div>
      );
    }
    return (
      <TokenField
      key={name}
      path={name}
      value={value}
      baseValue={baseValue}
      onChange={(v) => setAt(path, v)}
      />
    );
  };

  return (
    <div style={{
      flex: 1, display: "flex",
      flexDirection: isMobile ? "column" : "row",
      overflow: "hidden", background: palette.bg,
    }}>
    {/* ── Controls: ACTIVE theme, never the draft. See the header. ────── */}
    <div style={{
      flex: isMobile ? "none" : "0 0 380px",
      overflowY: "auto", padding: space.xl,
      borderRight: isMobile ? "none" : `1px solid ${palette.border}`,
      borderBottom: isMobile ? `1px solid ${palette.border}` : "none",
    }}>
    <div style={{
      color: palette.amber, fontSize: type.size.xs,
      letterSpacing: type.tracking.max, fontWeight: type.weight.bold,
      paddingBottom: space.sm,
      borderBottom: `1px solid ${palette.border}`,
      marginBottom: space.lg,
    }}>
    THEME EDITOR
    </div>

    <div style={{
      color: palette.muted, fontSize: type.size.sm,
      lineHeight: type.leading.relaxed, marginBottom: space.xl,
    }}>
    Developer tool. Edits a draft in memory only — nothing is saved and
    the selected theme is untouched.
    </div>

    <div style={{ display: "flex", gap: space.sm, marginBottom: space.xl }}>
    {Object.values(themes).map((t) => {
      const on = t.id === baseId;
      return (
        <button
        key={t.id}
        onClick={() => resetTo(t.id)}
        aria-pressed={on}
        style={{
          flex: 1, padding: `${space.xs}px ${space.sm}px`,
          background: on ? alpha(palette.amber, ALPHA.low) : "transparent",
              border: `1px solid ${on ? palette.amber : palette.border}`,
              borderRadius: radius.sm,
              color: on ? palette.amber : palette.text,
              fontSize: type.size.xs, fontFamily: type.family,
              fontWeight: type.weight.bold,
              letterSpacing: type.tracking.wide, cursor: "pointer",
        }}
        >
        {t.label.toUpperCase()}
        </button>
      );
    })}
    </div>

    <Group
    label="IDENTITY"
    count={IDENTITY_KEYS.length}
    open={open.has("identity")}
    onToggle={() => toggle("identity")}
    >
    {IDENTITY_KEYS.map((k) => renderValue([k], inputs[k], base[k]))}
    </Group>

    {Object.entries(GROUP_LABELS).map(([key, label]) => (
      <Group
      key={key}
      label={label}
      count={leafCount(inputs[key])}
      open={open.has(key)}
      onToggle={() => toggle(key)}
      >
      {Object.entries(inputs[key]).map(([k, v]) =>
        renderValue([key, k], v, base[key][k]))}
        </Group>
    ))}

    <Group
    label="EXPORT"
    count={sourceError ? "!" : "ok"}
    open={open.has("export")}
    onToggle={() => toggle("export")}
    >
    {sourceError ? (
      <div
      data-testid="export-error"
      style={{
        color: palette.red, fontSize: type.size.sm,
        fontFamily: type.mono, lineHeight: type.leading.relaxed,
        padding: space.sm,
        border: `1px solid ${palette.red}`,
        borderRadius: radius.sm,
      }}
      >
      {sourceError}
      </div>
    ) : (
      <>
      <div style={{
        color: palette.muted, fontSize: type.size.sm,
        lineHeight: type.leading.relaxed, marginBottom: space.sm,
      }}>
      Paste into frontend/src/theme.jsx, then add{" "}
      <span style={{ color: palette.amber, fontFamily: type.mono }}>
      {inputs.id}
      </span>{" "}
      to the themes export at the bottom of that file.
      </div>

      {/* Shown as well as downloaded. Copying out of here is faster
        * than a round trip through the filesystem for a one-line
        * tweak, and what is on screen is byte-identical to what the
        * button writes. */}
        <textarea
        data-testid="export-source"
        aria-label="theme source"
        readOnly
        value={source}
        rows={10}
        style={{
          ...inputStyle({ palette, type, space, radius }),
         width: "100%", resize: "vertical",
         whiteSpace: "pre", overflowWrap: "normal",
         fontSize: type.size.xs,
         lineHeight: type.leading.snug,
        }}
        />

        <button
        onClick={download}
        style={{
          marginTop: space.sm, width: "100%",
          padding: `${space.xs}px ${space.sm}px`,
          background: alpha(palette.amber, ALPHA.low),
         border: `1px solid ${palette.amber}`,
         borderRadius: radius.sm,
         color: palette.amber,
         fontSize: type.size.xs, fontFamily: type.family,
         fontWeight: type.weight.bold,
         letterSpacing: type.tracking.wide, cursor: "pointer",
        }}
        >
        DOWNLOAD {inputs.id}.theme.js
        </button>
        </>
    )}
    </Group>
    </div>

    {/* ── Preview: a real page under the draft ────────────────────────── */}
    <div
    data-testid="theme-preview"
    style={{
      flex: 1, overflowY: "auto",
      background: draft.palette.bg, color: draft.palette.text,
    }}
    >
    <ThemeContext.Provider
    value={{ ...draft, themeId: draft.id, setThemeId: () => {} }}
    >
    {children}
    </ThemeContext.Provider>
    </div>
    </div>
  );
};
